spring:
  application:
    name: vue-admin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vue-admin?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
      username: root
      password: 123456

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

mybatis:
  # 指定mybatis的mapper文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  #指定mybatis的实体目录
  type-aliases-package: com.yanxi.**.entity
  configuration:
    # 主键自增
    use-generated-keys: true
    # 驼峰映射
    map-underscore-to-camel-case: true
    # sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: secret-key
  # 令牌有效期（默认30分钟）
  expireTime: 30

  #redis 配置
  ##默认密码为空
  redis:
    host: 49.235.52.198
    # Redis服务器连接端口
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
